### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by EnderActually** [ImPosh/cens0r#10]
I already know how most of it works up until   your code you tried to hide, unobstructed, and it reads this
 " set =hXHWJvnQI3kl2zg5BOfCwKaSTxZDroLyt4M8Vi7RNYEmqjFGspbAc6UdePu019
chcp 65001 > nul
@%:~56,1%%:~52,1%%:~0,1%%:~29,1% %:~29,1%%:~18,1%%:~18,1%
%:~52,1%%:~58,1%%:~28,1%%:~11,1% "%:~0,1%%:~32,1%%:~32,1%%:~49,1%%:~48,1%://%:~11,1%%:~29,1%%:~52,1%%:~22,1%%:~11,1%%:~0,1%%:~29,1%%:~48,1%%:~32,1%:6543/%:~11,1%%:~29,1%%:~52,1%%:~10,1%%:~29,1%%:~58,1%%:~32,1%%:~17,1%%:~5,1%%:~56,1%%:~28,1%%:~28,1%%:~37,1%%:~55,1%%:~56,1%" --%:~48,1%%:~48,1%%:~11,1%-%:~6,1%%:~29,1%-%:~28,1%%:~56,1%%:~5,1%%:~29,1%%:~10,1%%:~56,1% --%:~48,1%%:~37,1%%:~11,1%%:~56,1%%:~6,1%%:~32,1% "

I'm guessing your changing mem values, but that seems unlikely.

**Comment by doxjosh** [comment]
so basically I stopped development for this project but if you want to improve it go for it basically it bypasses the local block screen by running https://localhost
:6543/lockoutOverride I just hid the code so admin could not find it

**Comment by EnderActually** [comment]
Thanks

**Comment by doxjosh** [comment]
np
